name: pengaduan_warga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  http: ^1.2.1
  get_it: ^7.7.0
  intl: ^0.19.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  cloud_firestore: ^5.1.0
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  responsive_grid: ^2.4.4
  dartz: ^0.10.1
  photo_view: ^0.15.0
  image: ^4.2.0
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.3.0
  equatable: ^2.0.5
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  shimmer: ^3.0.0
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  change_app_package_name: ^1.3.0
  freezed: ^2.5.2
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  web: 
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_stikom.png
    - assets/images/app_icon_removebg.png
    - assets/images/app_icon_modified.png
    - assets/keys/serviceAccountKey.json
